import { MoneroNode } from '../types/wallet';

export const DEFAULT_NODES: MoneroNode[] = [
  // 1. Tor Onion Nodes (Feather Wallet backbone)
  {
    id: 'tor-monerolove',
    name: 'MoneroLove Onion (Tor)',
    url: 'http://loveanvthlsepingenr7opdqy6nlhn5jidwvzzxfmwsw2rry5mn2gfqd.onion:18089',
    type: 'tor_onion',
    isTor: true,
    height: 3248912,
    targetHeight: 3248912,
    latencyMs: 380,
    isOnline: true,
    isDefault: true,
  },
  {
    id: 'tor-plowsof',
    name: 'PlowsOf Onion (Tor)',
    url: 'http://plowsof3t5hogddwabaeiyrno25efmzfxyro2vligremt7sxpsclfaid.onion:18089',
    type: 'tor_onion',
    isTor: true,
    height: 3248912,
    targetHeight: 3248912,
    latencyMs: 420,
    isOnline: true,
  },
  {
    id: 'tor-rucknium',
    name: 'Rucknium Research Onion (Tor)',
    url: 'http://rucknium757bokwv3ss35ftgc3gzb7hgbvvglbg3hisp7tsj2fkd2nyd.onion:18081',
    type: 'tor_onion',
    isTor: true,
    height: 3248912,
    targetHeight: 3248912,
    latencyMs: 450,
    isOnline: true,
  },

  // 2. Local Full Node (Monero GUI full node self-sovereign)
  {
    id: 'local-fullnode',
    name: 'Local Daemon (127.0.0.1:18081)',
    url: 'http://127.0.0.1:18081',
    type: 'local_fullnode',
    isTor: false,
    height: 3248912,
    targetHeight: 3248912,
    latencyMs: 4,
    isOnline: true,
  },

  // 3. Curated Clearnet Nodes (Fallback with privacy posture warning)
  {
    id: 'clearnet-seth',
    name: 'SethForPrivacy Curated Node',
    url: 'https://node.sethforprivacy.com:18089',
    type: 'clearnet_curated',
    isTor: false,
    height: 3248912,
    targetHeight: 3248912,
    latencyMs: 65,
    isOnline: true,
  },
  {
    id: 'clearnet-cake',
    name: 'Cake Wallet Public Node',
    url: 'https://xmr-node.cakewallet.com:18081',
    type: 'clearnet_curated',
    isTor: false,
    height: 3248912,
    targetHeight: 3248912,
    latencyMs: 82,
    isOnline: true,
  },
  {
    id: 'clearnet-monerodevs',
    name: 'Monero Devs Public Node',
    url: 'https://node.monerodevs.org:18089',
    type: 'clearnet_curated',
    isTor: false,
    height: 3248912,
    targetHeight: 3248912,
    latencyMs: 95,
    isOnline: true,
  },
];
